import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/shared/Navbar'
import LeftSidebar from '@/components/shared/LeftSidebar'
import Footer from '@/components/shared/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />

          <main className="flex flex-row">
            <LeftSidebar />
            <section className='flex min-h-screen flex-1 flex-col items-center bg-gray-950 px-6 pb-10 pt-28 max-md:pb-32 sm:px-10'>
              <div className='w-full max-w-4xl'>
                {children}
              </div>
            </section>
            {/* <RightSidebar /> */}
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}